### ISSUE TITLE
Request library update to v3.0.0-b9

### ISSUE THREAD

**Issue by zygon4** [SquidPony/DD-7dRL2018#1]
The game looks built against a git hash from the March timeframe. Any chance it could get an update to the latest beta?

Thanks!

-Z

**Comment by tommyettinger** [comment]
3.0.0-b9 is... I think significantly older than that git hash. I've been negligent with beta release versions of SquidLib. I'll update the version DD depends on (if I can commit here, anyway... I think I can since I remember writing code for some features). I don't anticipate much has changed in a breaking way.

**Comment by zygon4** [comment]
> 3.0.0-b9 is... I think significantly older than that git hash.

Oh, I off-by-one'd the year in my head, I thought the v3b9 came out recently _this_ year. My bad!

**Comment by tommyettinger** [comment]
The latest commit to DD-7dRL2018 now uses the SquidLib commit from November 6, 2018 (today). Are you planning to use this for something? It's kinda hacked together from Epigon code, https://github.com/SquidPony/Epigon , and jumbled around to make a completely different game.

**Comment by zygon4** [comment]
Yeah I realized that after I opened the issue. I've been looking for a Java-based RL to hack up. Epigon itself looks a little more sane to start with :)

**Comment by tommyettinger** [comment]
It *might* be considered sane... the code is rather messy from multiple partial rewrites, but it looks nice! There's lights all over the place! There's also a zillion kinds of weapon and material, as any roguelike strives for, it seems. The Modification system is a key part of the code but also one of the ugliest sections of it, with lots of weird placement (RecipeMixer is needed to use Modification, for instance) and code duplication. If you want to hack it up, I'd probably start by ripping out Modification and trying to replace it with something that fits your vision better.

**Comment by SquidPony** [comment]
The other awkward thing about Modification is that the RecipeMixer only partially implements it. Basically more complete use of Modification has only been added as needed.

I agree with Tommy that almost certainly pulling out Modification is a good idea. It's primarily there to support too-big-to-ever-finish ideas about object mutability in a roguelike setting, probably not needed :)
